name: event_kita_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  uuid: ^4.5.1
  intl: ^0.20.2
  flutter_map: ^8.1.1
  http: ^1.4.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5


flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/